KAN-112  feat: 블로그 후기 기능 구현
kakaotech-bootcamp-22/be pull request #14
Opened 2024-12-02 10:05 UTC by sall6550

### 🔗 관련 이슈
[KAN-112](https://ktb-22.atlassian.net/jira/software/projects/KAN/boards/1?selectedIssue=KAN-112
)

### 📌 작업 내용
- 리뷰 및 별점 통계를 반환하는 API 추가
- 블로그 후기 등록 기능 추가
- 하트 클릭시 count 기능 추가
- 페이지네이션 구현
- PATCH 메서드 사용을 위한 보안 설정 변경
- 유저별 리뷰1개씩만 등록할수있게 처리
- 좋아요 유저당1번씩 눌리게 변경
- 유저리뷰 sorting API 개선

### 🧑‍💻 작업 유형
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD 변경

### 📷 관련 이미지

### 🚨 주의 사항
테스트 해 보려면 blog테이블에 값이 존재해야하는데 해당부분이 미구현상태라 
INSERT INTO public.blogs (blog_id, blog_url, review_count)
VALUES (1, 'blog.naver.com/kakao_food_fighter', 0);
쿼리로 임의로 값을 넣고 테스트해볼수있습니다.

### ✅ 체크 리스트
- [x] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트 했습니다.
- [x] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

[KAN-112]: https://ktb-22.atlassian.net/browse/KAN-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +    public ResponseEntity<BlogReviewResponseDto> getBlogReviews(@PathVariable Long blog_id) {
왜 요기는 스네이크 케이스로 받으신걸까요??

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +            String token = CookieUtils.extractTokenFromCookie(cookieHeader, "jwtToken");
\@CookieValue("jwtToken")로 가져오는게 편하지 않았을까요?

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +            return ResponseEntity.status(401).body(null);
로그인에 대한 처리는 앞단의 필터에서 다 해주는게 맞을것 같아요

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +        return ResponseEntity.ok("좋아요 증가");
응답은 Json으로 내리는게 좋구요
굳이 내릴정보가 없지만 200(OK)를 쓰면서 명목상 내리는 응답을 쓸바에야 204(No Content)를 사용하는게 좋아요~!

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +    public Page<ReviewDto> getReviewsByRatingAsc(@PathVariable Long blogId,
ㅋㅋㅋ 요렇게 소팅별로 API를 따로 구현하는것 보다 파라메터를 하나 더 받아서 한개의 API로 처리하는게 좋아요!

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/dto/BlogReviewResponseDto.java
> +}
<img width="212" alt="스크린샷 2024-12-03 오후 3 26 31" src="https://github.com/user-attachments/assets/d6a1ad47-7e12-4012-8763-a48439790f6f">
파일 끝 개행 설정은 넣어주세요~!

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Invalid blog ID"));
이때는 404(Not Found)를 쓰는게 좋을듯하네요

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +    }
요 메소드는 트랜잭션으로 동작해야할것 같아요!

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
요 코드 동시성 이슈 발생하기 정말 좋아보이네요 ㅋㅋㅋ
만약 두명의 유저가 한개의 리뷰에 정말 동시에 좋아요를 누르면 하나의 요청은 무시될법 하네요

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
그리고 기획에 관련해서 궁금한건데 같은 유저가 좋아요를 여러번 누를수 있나요??
혹시 그게아니라면 이미 좋아요를 눌렀다면 두번눌렀을때 취소되거나 최소한 두번은 못하게 막아야 할듯하네요 ㅋㅋㅋ

2024-12-03 06:37 UTC, konempty commented on src/main/java/com/spring/be/entity/BlogReview.java
> +import lombok.*;
와일드카드 임포트는 지양하셔야합니다 ㅠㅠ
[참고](https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad)

2024-12-03 10:20 UTC, dayaelee requested changes

2024-12-03 10:20 UTC, dayaelee commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
방금 확인해보니 같은 유저가 좋아요를 여러번 눌렀을때 그대로 카운팅 되고있어서 그 부분은 인당 하나의 리뷰에 대해서 좋아요 카운트는 하나만 할수있게끔 변경하는 것이 좋겠습니다

2024-12-03 10:20 UTC, dayaelee commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +
같은 유저가 하나의 블로그에 대해 여러번 다양한 별점의 리뷰 혹은 이미 등록한 별점의 리뷰를 중복으로 추가할 수 있는데 하나의 블로그에 대해 유저당 하나의 리뷰만 등록할 수 있게 하셔야 별점 평균낼때 의미가 있을 것으로 보입니다!

2024-12-03 10:35 UTC, dayaelee requested changes
전체적으로 구현해주시느라 고생하셨습니다! 상기 피드백 드린 부분 잘 고려하시어 개선해주셨으면 좋겠습니다!

2024-12-03 14:10 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +    public ResponseEntity<BlogReviewResponseDto> getBlogReviews(@PathVariable Long blog_id) {
아무생각없이 저렇게 적었네요.. 수정완료했습니다!!

2024-12-03 14:15 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +            String token = CookieUtils.extractTokenFromCookie(cookieHeader, "jwtToken");
CookieValue는 처음알았네요! 적용완료했습니다

2024-12-03 14:40 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +            return ResponseEntity.status(401).body(null);
해당부분 로그인구현한 팀원분이랑 논의해보겠습니다!

2024-12-03 14:58 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +        return ResponseEntity.ok("좋아요 증가");
해당부분 어떻게 처리해야하나 고민이었는데 감사합니다 수정했습니다!

2024-12-03 16:25 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +    public Page<ReviewDto> getReviewsByRatingAsc(@PathVariable Long blogId,
감사합니다 수정했습니다!

2024-12-03 16:28 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/dto/BlogReviewResponseDto.java
> +}
수정했습니다!

2024-12-03 16:33 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Invalid blog ID"));
수정했습니다!

2024-12-03 16:36 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +    }
@Transactional 추가했습니다!

2024-12-04 04:49 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
동시성이슈에대해 처음 알았습니다 동시성이슈가 발생하지않게 쿼리하나로 처리했습니다!

2024-12-04 05:36 UTC, konempty commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
@sall6550 으흠 ㅋㅋㅋ 동시성 이슈를 쿼리만으론 해결이 어려울텐데 어떤식으로 처리했을지 기대되네요

2024-12-04 05:46 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
@Modifying
    @Query("UPDATE BlogReview br SET br.likesCnt = br.likesCnt + 1 WHERE br.blogReviewId = :reviewId")
    int incrementLikes(@Param("reviewId") Long reviewId);
    이걸로 동시성이슈를 처리했으나 이건 좋아요기능을 여러번 누를수있을때이고
    
    좋아요기능을 한번누르면 +1 한번더 누르면 -1 로 바꾸는과정에서는 저방법이 불가능한거 같아 낙관적 락이랑 비관적 락중 어느걸 사용해야할지 고민중에있습니다..!!

2024-12-04 06:36 UTC, nuyeo requested changes
고생하셨습니다~!

2024-12-04 06:36 UTC, nuyeo commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
좋아요 누르기도 로그인 상태에서만 가능하도록 수정이 필요할 것 같습니다!

2024-12-04 06:52 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
해당부분 아이비님한테 jwt필터단에서 처리해달라해서 적용되면 자동처리될거같습니다!

2024-12-04 18:49 UTC, sall6550 commented on src/main/java/com/spring/be/entity/BlogReview.java
> +import lombok.*;
인텔리제이에서 자동임포트 설정을 해놨는데 
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
까지는 하나씩 임포트해주다가 @Setter 까지 넣으면 다 지워버리고 *로 바꿔버리네요.. 주의해야겠습니다!

2024-12-04 19:13 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
비관적 락 방식으로 구현하였습니다! 더 좋은 최적화방식이 있을거같은데 현재 지식이 부족해서 추후 좀 더 공부 후 리팩토링, 테스트코드 작성예정입니다 좋은주제 감사합니다!

2024-12-04 19:31 UTC, sall6550 commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +
해당사항 수정했습니다!

2024-12-05 09:44 UTC, dayaelee commented on src/main/java/com/spring/be/blogReview/service/BlogReviewService.java
> +        review.setLikesCnt(review.getLikesCnt() + 1);
확인했습니다!

2024-12-05 09:44 UTC, dayaelee commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +            return ResponseEntity.status(401).body(null);
확인했습니다!

2024-12-05 09:46 UTC, dayaelee commented on src/main/java/com/spring/be/blogReview/controller/BlogReviewController.java
> +            String token = CookieUtils.extractTokenFromCookie(cookieHeader, "jwtToken");
확인했습니다! 저도 관련 부분 반영하겠습니다!

2024-12-05 09:47 UTC, dayaelee approved these changes
수정사항 테스트하여 정상작동 하는것 확인했습니다! 
제 파트 관련 부분은 저도 리뷰 참고하여 곧 커밋 올리겠습니다! 
고생하셨습니다!

2024-12-06 07:15 UTC, merged