KAN-145 fix: 회원탈퇴 및 사용자 상태 확인 버그 수정 및 안정화
kakaotech-bootcamp-22/be pull request #19
Opened 2024-12-20 12:37 UTC by dayaelee

### 🔗 관련 이슈
KAN-145

### 📌 작업 내용

- 회원 탈퇴 api 호출 로직 추가
- 회원 탈퇴시 유저 정보 리셋 (닉네임, 이미지)
- 로그인 api처리후 리다이렉트를 위한 로직 추가 

### 🧑‍💻 작업 유형
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD 변경

### 🚨 주의 사항
배포시에 배포를 위한 코드 수정이 필요함
-httpOnly 설정 변경 필요
-리다이렉트 관련 파라미터 스토어 값 변경 필요 

### ✅ 체크 리스트
- [ ] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트 했습니다.
- [ ] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

2024-12-22 06:58 UTC, sall6550 requested changes

2024-12-22 06:58 UTC, sall6550 commented on src/main/java/com/spring/be/jwt/controller/AuthController.java
> +    }
<img width="856" alt="image" src="https://github.com/user-attachments/assets/c7c31bc5-54fd-478b-8a9e-8fa2b3a09d1f" />
예전에 멘토님이 언급해주셨던건데 아직 < ? > 로 되어있는부분이 많더라고요 동적으로 타입이 바뀌는게아니면 지정해주는게 좋을거같습니다

2024-12-22 06:58 UTC, sall6550 commented on src/main/java/com/spring/be/jwt/service/AuthService.java
> +    public ResponseEntity<?> performKakaoUnlink(String token) {
서비스코드에서 ResponseEntity 가 쓰인거같은데 서비스코드에서 쓰는게아닌 컨트롤러에서 사용하셔야합니다 수정부탁드립니다.

2024-12-22 06:58 UTC, sall6550 commented on src/main/java/com/spring/be/jwt/service/AuthService.java
> +    public ResponseEntity<?> deleteUser(String jwtToken) {
서비스코드에서 ResponseEntity 가 쓰인거같은데 서비스코드에서 쓰는게아닌 컨트롤러에서 사용하셔야합니다 수정부탁드립니다.

2024-12-22 06:58 UTC, sall6550 commented on src/main/java/com/spring/be/jwt/service/AuthService.java
> +        ResponseEntity<?> logoutResponse;
수정부탁드립니다

2024-12-23 04:19 UTC, konempty commented on src/main/java/com/spring/be/jwt/controller/AuthController.java
>  }
<img width="101" alt="스크린샷 2024-12-20 오후 11 13 44" src="https://github.com/user-attachments/assets/24ea6027-5f4d-413b-9a0c-3dcbaac440f1" />

파일끝 개행 설정해주세요!
[참고](https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/)

2024-12-23 04:19 UTC, konempty commented on src/main/java/com/spring/be/jwt/controller/GoogleAuthController.java
> +                .httpOnly(false)// 테스트용 - false
테스트가 끝나면 롤백해야할것 같아요!
아니면 아직도 테스트 중인걸까요?

2024-12-23 04:36 UTC, dayaelee commented on src/main/java/com/spring/be/jwt/controller/GoogleAuthController.java
> +                .httpOnly(false)// 테스트용 - false
네 맞습니다 아직 테스트중이에요 ㅠ 배포하실떄 따로 말해주시면 수정해드린다고 말씀드렸어요!

2024-12-23 07:08 UTC, dayaelee commented on src/main/java/com/spring/be/jwt/controller/AuthController.java
> +    }
관련한 부분 수정하였습니다!

2024-12-23 09:01 UTC, dayaelee commented on src/main/java/com/spring/be/jwt/service/AuthService.java
> +    public ResponseEntity<?> performKakaoUnlink(String token) {
관련 부분 수정했습니다!

2024-12-23 09:01 UTC, dayaelee commented on src/main/java/com/spring/be/jwt/service/AuthService.java
> +    public ResponseEntity<?> deleteUser(String jwtToken) {
관련 부분 수정했습니다!

2024-12-23 09:02 UTC, dayaelee commented on src/main/java/com/spring/be/jwt/service/AuthService.java
> +        ResponseEntity<?> logoutResponse;
관련 부분 수정했습니다!

2024-12-23 09:03 UTC, dayaelee commented on src/main/java/com/spring/be/jwt/controller/AuthController.java
>  }
아하 해당 부분 빠져있네요 확인후 수정했습니다!

2024-12-24 18:24 UTC, nuyeo approved these changes
고생하셨습니다~

2024-12-25 13:56 UTC, merged